/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordmanagersystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class categoryp extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form category
     */
    public categoryp() {
        initComponents();
    
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= passworddata.java_db();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        curi = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        editC = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        addC = new javax.swing.JButton();
        deleteC1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();
        showdataT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(10.5F);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel6.setText("URI Category ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel7.setText("Category OF Password ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 50));

        curi.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        curi.setForeground(new java.awt.Color(51, 153, 255));
        curi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        curi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));
        curi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curiActionPerformed(evt);
            }
        });
        jPanel3.add(curi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 370, 40));

        cname.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        cname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel3.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 370, 40));

        editC.setBackground(new java.awt.Color(255, 255, 255));
        editC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EditRecod.png"))); // NOI18N
        editC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCActionPerformed(evt);
            }
        });
        jPanel3.add(editC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 60, 60));

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 60, 60));

        addC.setBackground(new java.awt.Color(255, 255, 255));
        addC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ADDrecord1.png"))); // NOI18N
        addC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCActionPerformed(evt);
            }
        });
        jPanel3.add(addC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 60, 60));

        deleteC1.setBackground(new java.awt.Color(255, 255, 255));
        deleteC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deleteRecord.png"))); // NOI18N
        deleteC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteC1ActionPerformed(evt);
            }
        });
        jPanel3.add(deleteC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 60, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 230));

        ctable.setBackground(new java.awt.Color(204, 204, 255));
        ctable.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ctable.setForeground(new java.awt.Color(204, 51, 255));
        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Category Name", "Category URI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ctable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ctable.setGridColor(new java.awt.Color(204, 0, 204));
        ctable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ctable.setRowHeight(30);
        ctable.setSelectionBackground(new java.awt.Color(153, 102, 255));
        ctable.setSelectionForeground(new java.awt.Color(153, 51, 255));
        ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1020, 410));

        showdataT.setBackground(new java.awt.Color(255, 255, 255));
        showdataT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showdataT.setForeground(new java.awt.Color(255, 0, 0));
        showdataT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_View_Details_26px.png"))); // NOI18N
        showdataT.setText(" Show Data");
        showdataT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdataTActionPerformed(evt);
            }
        });
        jPanel2.add(showdataT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ctree.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 360, 290));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel1.setText("Category of Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 190, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Manager");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 160, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PasswordLockLOGO.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void curiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curiActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void addCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO categroy"
                    + " (Cname,curi) VALUES(?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cname.getText());
            pst.setString(2, curi.getText());
            pst.execute();
            
           JOptionPane.showMessageDialog(null,"Add Category Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
//            conn.close();
        }catch(Exception e){ 
        }
        }          
    }//GEN-LAST:event_addCActionPerformed

    private void editCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCActionPerformed
        // TODO add your handling code here:
        try{
            String val1=cname.getText();
            String val2=curi.getText();

            
            String sql="UPDATE categroy set Cname='"+val1+"', curi='"+val2+"' WHERE Cname='"+val1+"' ";
            pst =conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Category Uptdated Successfuly...");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
//                conn.close();
            }catch(Exception e){
                
            }

            }
    }//GEN-LAST:event_editCActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        cname.setText("");
        curi.setText("");
    }//GEN-LAST:event_refreshActionPerformed

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased
        // TODO add your handling code here:
        try{
            String sql="select * from categroy where Cname = ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cname.getText());
            rs=pst.executeQuery();
    
            String add1=rs.getString("Cname");
            cname.setText(add1);
            String add2=rs.getString("curi");
            curi.setText(add2);
        }catch(Exception e){
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_cnameKeyReleased

    private void showdataTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdataTActionPerformed
        // TODO add your handling code here:.
            try{
        String sql = "select * from categroy";
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next()){
            String id=String.valueOf(rs.getInt("no"));
            String Cname=rs.getString("Cname");
            String Curi=rs.getString("curi");
            
            String tbData[]={id,Cname,Curi};
            DefaultTableModel tbModel =(DefaultTableModel)ctable.getModel();
            
            tbModel.addRow(tbData);
    
    }
//        JOptionPane.showMessageDialog(null,"Add Category Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rs.close();
            pst.close();
//           conn.close();
        }catch(Exception e){ 
        }
    }
    }//GEN-LAST:event_showdataTActionPerformed

    private void ctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)ctable.getModel();
        int Myindex =ctable.getSelectedRow();
        
        cname.setText(model.getValueAt(Myindex, 1).toString());
        curi.setText(model.getValueAt(Myindex, 2).toString());
    }//GEN-LAST:event_ctableMouseClicked

    private void deleteC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteC1ActionPerformed
        // TODO add your handling code here:
                try{
            String sql="DELETE FROM categroy where Cname = ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cname.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Categroy Deleted Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
//                conn.close();
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_deleteC1ActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        dashboard  j=new dashboard();
            j.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categoryp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categoryp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categoryp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categoryp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categoryp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JButton addC;
    private javax.swing.JTextField cname;
    private javax.swing.JTable ctable;
    private javax.swing.JTextField curi;
    private javax.swing.JButton deleteC1;
    private javax.swing.JButton editC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton showdataT;
    // End of variables declaration//GEN-END:variables
}
