/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordmanagersystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLEncoder;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Random;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class viewpass extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form viewpass
     */
    public viewpass() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2- getHeight()/2);
        conn= passworddata.java_db();         
    }

    public static void sendSms(String message,String number){
		try{		
		String apiKey="E8sYwxAyOaLXoW21tHhinpNzRfIbjPeqvgVUlBTd9K53ZDmScushzka4pcrJimYHLjDT9xZISoenEBMP";
		String sendId="FSTSMS";
		message=URLEncoder.encode(message, "UTF-8");
		String language="english";
		String route="p";
		String myUrl="https://www.fast2sms.com/dev/bulk?authorization="+apiKey+"&sender_id="+sendId+"&message="+message+"&language="+language+"&route="+route+"&numbers="+number;
		URL url=new URL(myUrl);
		HttpsURLConnection con=(HttpsURLConnection)url.openConnection();		
		con.setRequestMethod("GET");		
		con.setRequestProperty("User-Agent", "Mozilla/5.0");
		con.setRequestProperty("cache-control", "no-cache");
		System.out.println("Wait..............");		
		int code=con.getResponseCode();		
		System.out.println("Response code : "+code);		
		StringBuffer response=new StringBuffer();		
		BufferedReader br=new BufferedReader(new InputStreamReader(con.getInputStream()));		
		while(true){
			String line=br.readLine();
			if(line==null){
				break;
			}
			response.append(line);
		}		
		System.out.println(response);                                      
                JOptionPane.showMessageDialog(null,"Your Password Send successfully (^o^) ");		
		}catch (Exception e) {
			e.printStackTrace();
		}		
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        showopassdataT = new javax.swing.JButton();
        refresh = new javax.swing.JLabel();
        getpass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        delete = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        showpass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel1.setText("View Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 240, 40));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Manager");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 160, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PasswordLockLOGO.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 50, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ptable.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category Name", "Category URI", "User Name", "Password", "Password Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ptable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ptable.setRowHeight(25);
        ptable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        ptable.setSelectionForeground(new java.awt.Color(51, 51, 255));
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1010, 420));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("Category Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setText("User Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 40));

        uname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 51, 51));
        uname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel2.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 340, 30));

        cname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cname.setForeground(new java.awt.Color(255, 51, 51));
        cname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnameKeyReleased(evt);
            }
        });
        jPanel2.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 340, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setText("Mobile NO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 40));

        pass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 51, 51));
        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 340, 30));

        showopassdataT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showopassdataT.setForeground(new java.awt.Color(255, 0, 0));
        showopassdataT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_View_Details_26px.png"))); // NOI18N
        showopassdataT.setText(" Show Data");
        showopassdataT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showopassdataTActionPerformed(evt);
            }
        });
        jPanel2.add(showopassdataT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 160, -1));

        refresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 60, 50));

        getpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getpass.setForeground(new java.awt.Color(0, 0, 255));
        getpass.setText("Get Password");
        getpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getpassMouseClicked(evt);
            }
        });
        jPanel2.add(getpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 90, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator1.setAlignmentY(2.0F);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 90, 10));

        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deleteRecord.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 60, 50));

        mobile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mobile.setForeground(new java.awt.Color(255, 51, 51));
        mobile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        jPanel2.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 340, 30));

        showpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/viewpass.png"))); // NOI18N
        showpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showpassMouseExited(evt);
            }
        });
        jPanel2.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        dashboard  j=new dashboard();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void cnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameKeyReleased

    private String md5(String c){
      try{
          MessageDigest digs =MessageDigest.getInstance("MD5");
          digs.update((new String(c)).getBytes("UTF8"));
          String str= new String(digs.digest());
          return str;
            //        JOptionPane.showMessageDialog(null,"Add Category Successfully...");
        }catch(Exception e){
            return "";
        }  
    }
    private void showopassdataTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showopassdataTActionPerformed
        // TODO add your handling code here:.
        try{
         String sql="select * from passrecord";
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        
        
        while(rs.next()){
          
            String Cname=rs.getString("Cname");
            String Curi=rs.getString("curi");
            String Uname=rs.getString("uname");
            String p=rs.getString("pass");
            String pass=md5(p);
            String Passd=rs.getString("passd");
            
            String tbData[]={Cname,Curi,Uname,pass,Passd};
            DefaultTableModel tbModel =(DefaultTableModel)ptable.getModel();
            
            tbModel.addRow(tbData);
        }
            //        JOptionPane.showMessageDialog(null,"Add Category Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
                //           conn.close();
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_showopassdataTActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)ptable.getModel();
        int Myindex =ptable.getSelectedRow();
        
        cname.setText(model.getValueAt(Myindex, 0).toString());
        uname.setText(model.getValueAt(Myindex, 2).toString());
        
    }//GEN-LAST:event_ptableMouseClicked

    private void getpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getpassMouseClicked
        // TODO add your handling code here:
        try{        
            String sql="select * from passrecord where(Cname = ? and uname = ? and mo=? )";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, cname.getText());
            pst.setString(2, uname.getText());
            pst.setString(3, mobile.getText());
            rs=pst.executeQuery();
            
 
            
            String add2=rs.getString("uname");
            String add3=rs.getString("pass");
            pass.setText(add3);
            String Message="Your User_Name is "+ add2+" \n and password is : "+ add3 ;
            viewpass.sendSms(Message, mobile.getText());
           
    }catch(Exception e){
          JOptionPane.showMessageDialog(null,"your mobile no is not mached..."); 
        } 
        finally{
        try{
            rs.close();
            pst.close();
        }catch(Exception e){
        
        }
        }      
        
    }//GEN-LAST:event_getpassMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        cname.setText("");
        uname.setText("");
        mobile.setText("");
        pass.setText("");
    }//GEN-LAST:event_refreshMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
         try{
            String sql="DELETE FROM passrecord where(Cname = ? and uname = ? )";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cname.getText());
            pst.setString(2, uname.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Password Deleted Successfully...");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
//                conn.close();
            }catch(Exception e){

            }
        }        
    }//GEN-LAST:event_deleteMouseClicked

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void showpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseClicked
        // TODO add your handling code here:
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_showpassMouseClicked

    private void showpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassMouseExited
        // TODO add your handling code here:
        pass.setEchoChar('*');
    }//GEN-LAST:event_showpassMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel getpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTable ptable;
    private javax.swing.JLabel refresh;
    private javax.swing.JButton showopassdataT;
    private javax.swing.JLabel showpass;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
